//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackCoinMultipool.UI.WindowsPhone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackCoinMultipool.UI.WindowsPhone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is in no way affiliated with BlackCoin. The source of this application is released under the Microsoft Public License (MS-PL) and is available on github.com/auspex-nl..
        /// </summary>
        public static string AboutApplicationText {
            get {
                return ResourceManager.GetString("AboutApplicationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT THIS APPLICATION.
        /// </summary>
        public static string AboutApplicationTitle {
            get {
                return ResourceManager.GetString("AboutApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rick Jansen
        ///Website: auspex.nl
        ///Github: github.com/auspex-nl.
        /// </summary>
        public static string AboutDeveloperText {
            get {
                return ResourceManager.GetString("AboutDeveloperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE DEVELOPER.
        /// </summary>
        public static string AboutDeveloperTitle {
            get {
                return ResourceManager.GetString("AboutDeveloperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MvvmCross 
        ///MvvmCross plugins by ACR.
        /// </summary>
        public static string AboutLibrariesText {
            get {
                return ResourceManager.GetString("AboutLibrariesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3RD PARTY LIBRARIES.
        /// </summary>
        public static string AboutLibrariesTitle {
            get {
                return ResourceManager.GetString("AboutLibrariesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLACKCOIN POOL.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to immature.
        /// </summary>
        public static string BalancesImmature {
            get {
                return ResourceManager.GetString("BalancesImmature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ready for payout.
        /// </summary>
        public static string BalancesReadyForPayout {
            get {
                return ResourceManager.GetString("BalancesReadyForPayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total expected.
        /// </summary>
        public static string BalancesTotalExpected {
            get {
                return ResourceManager.GetString("BalancesTotalExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexchanged.
        /// </summary>
        public static string BalancesUnexchanged {
            get {
                return ResourceManager.GetString("BalancesUnexchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC.
        /// </summary>
        public static string BC {
            get {
                return ResourceManager.GetString("BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTC.
        /// </summary>
        public static string BTC {
            get {
                return ResourceManager.GetString("BTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy to clipboard.
        /// </summary>
        public static string DonateCopyToClipboard {
            get {
                return ResourceManager.GetString("DonateCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you find this application useful and want to donate some blackcoins to support development, please send any amount you want to the following blackcoin address:.
        /// </summary>
        public static string DonateText {
            get {
                return ResourceManager.GetString("DonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to automatic.
        /// </summary>
        public static string GettingStartedAutomatic {
            get {
                return ResourceManager.GetString("GettingStartedAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your blackcoin address.
        /// </summary>
        public static string GettingStartedEnterYourAddress {
            get {
                return ResourceManager.GetString("GettingStartedEnterYourAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button below to scan your blackcoin-address&apos;s QR code. You can also enter your blackcoin-address manually to the right.
        /// </summary>
        public static string GettingStartedExplanation {
            get {
                return ResourceManager.GetString("GettingStartedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is my QR Code?.
        /// </summary>
        public static string GettingStartedHelpQRCode {
            get {
                return ResourceManager.GetString("GettingStartedHelpQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manual.
        /// </summary>
        public static string GettingStartedManual {
            get {
                return ResourceManager.GetString("GettingStartedManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the blackcoin wallet on your pc or go to bitcoinqrcode.org to generate a valid QR Code for your blackcoin address..
        /// </summary>
        public static string GettingStartedQRCodePopupText {
            get {
                return ResourceManager.GetString("GettingStartedQRCodePopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string GettingStartedSave {
            get {
                return ResourceManager.GetString("GettingStartedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan QR code.
        /// </summary>
        public static string GettingStartedScanQR {
            get {
                return ResourceManager.GetString("GettingStartedScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHash/s.
        /// </summary>
        public static string GHashPerSecond {
            get {
                return ResourceManager.GetString("GHashPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash/s.
        /// </summary>
        public static string HashPerSecond {
            get {
                return ResourceManager.GetString("HashPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kHash/s.
        /// </summary>
        public static string kHashPerSecond {
            get {
                return ResourceManager.GetString("kHashPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donate.
        /// </summary>
        public static string MenuDonate {
            get {
                return ResourceManager.GetString("MenuDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MHash/s.
        /// </summary>
        public static string MHashPerSecond {
            get {
                return ResourceManager.GetString("MHashPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PageAbout {
            get {
                return ResourceManager.GetString("PageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scrypt hashrate.
        /// </summary>
        public static string PageCurrentHashrateScrypt {
            get {
                return ResourceManager.GetString("PageCurrentHashrateScrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sha256 hashrate.
        /// </summary>
        public static string PageCurrentHashrateSha256 {
            get {
                return ResourceManager.GetString("PageCurrentHashrateSha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string PageDonate {
            get {
                return ResourceManager.GetString("PageDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        public static string PageGettingStarted {
            get {
                return ResourceManager.GetString("PageGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shifts.
        /// </summary>
        public static string PageShifts {
            get {
                return ResourceManager.GetString("PageShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics.
        /// </summary>
        public static string PageStatistics {
            get {
                return ResourceManager.GetString("PageStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found address:.
        /// </summary>
        public static string PopupFoundAddress {
            get {
                return ResourceManager.GetString("PopupFoundAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this correct?.
        /// </summary>
        public static string PopupIsThisCorrect {
            get {
                return ResourceManager.GetString("PopupIsThisCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string PopupNo {
            get {
                return ResourceManager.GetString("PopupNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string PopupOK {
            get {
                return ResourceManager.GetString("PopupOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string PopupYes {
            get {
                return ResourceManager.GetString("PopupYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change address.
        /// </summary>
        public static string SettingsChangeAddress {
            get {
                return ResourceManager.GetString("SettingsChangeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currently set address:.
        /// </summary>
        public static string SettingsCurrentlySetAddress {
            get {
                return ResourceManager.GetString("SettingsCurrentlySetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current scrypt shares.
        /// </summary>
        public static string StatisticsCurrentSharesScrypt {
            get {
                return ResourceManager.GetString("StatisticsCurrentSharesScrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current sha256 shares.
        /// </summary>
        public static string StatisticsCurrentSharesSHA256 {
            get {
                return ResourceManager.GetString("StatisticsCurrentSharesSHA256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date joined.
        /// </summary>
        public static string StatisticsDateJoined {
            get {
                return ResourceManager.GetString("StatisticsDateJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string StatisticsDay {
            get {
                return ResourceManager.GetString("StatisticsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string StatisticsDays {
            get {
                return ResourceManager.GetString("StatisticsDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last 24h profits.
        /// </summary>
        public static string StatisticsLast24hProfits {
            get {
                return ResourceManager.GetString("StatisticsLast24hProfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest scrypt payout.
        /// </summary>
        public static string StatisticsLatestPayoutScrypt {
            get {
                return ResourceManager.GetString("StatisticsLatestPayoutScrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest sha256 payout.
        /// </summary>
        public static string StatisticsLatestPayoutSHA256 {
            get {
                return ResourceManager.GetString("StatisticsLatestPayoutSHA256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mining days.
        /// </summary>
        public static string StatisticsMiningDays {
            get {
                return ResourceManager.GetString("StatisticsMiningDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total profits.
        /// </summary>
        public static string StatisticsTotalProfits {
            get {
                return ResourceManager.GetString("StatisticsTotalProfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THash/s.
        /// </summary>
        public static string THashPerSecond {
            get {
                return ResourceManager.GetString("THashPerSecond", resourceCulture);
            }
        }
    }
}
